import "package:coderelay/models/song_model.dart";

final List<Song> songlist = [
  Song(
    title: "Beat It",
    artist: "Michael Jackson",
    album: "Thriller",
    year: "1983",
    audioUrl: "Beat It.mp3",
    imageUrl: "images/beat_it.jpg",
  ),
  Song(
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    year: "1982",
    audioUrl: "Billie Jean.mp3",
    imageUrl: "images/billie_jean.jpg",
  ),
  Song(
    title: "Can't Help Falling in Love",
    artist: "Elvis Presley",
    album: "Blue Hawaii (Soundtrack)",
    year: "1961",
    audioUrl: "Cant HelpFalling In Love.mp3",
    imageUrl: "images/cant_help_falling_in_love.jpg",
  ),
  Song(
    title: "Jam",
    artist: "Michael Jackson",
    album: "Dangerous",
    year: "1991",
    audioUrl: "Jam.mp3",
    imageUrl: "images/jam.jpg",
  ),
  Song(
    title: "Numb",
    artist: "Linkin Park",
    album: "Meteora",
    year: "2003",
    audioUrl: "Numb.mp3",
    imageUrl: "images/numb.jpg",
  ),
  Song(
    title: "Sweet Child o' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: "1987",
    audioUrl: "sweet_child_o_mine.mp3",
    imageUrl: "images/sweet_child_o_mine.jpg",
  ),
  Song(
    title: "Rumbling",
    artist: "Sim",
    album: "Play Dead",
    year: "2022",
    audioUrl: "rumbling.mp3",
    imageUrl: "images/rumbling.jpg",
  ),
  Song(
    title: "Thriller",
    artist: "Michael Jackson",
    album: "Thriller",
    year: "1982",
    audioUrl: "thriller.mp3",
    imageUrl: "images/thriller.jpg",
  ),
  Song(
    title: "Until I Found You",
    artist: "Stephen Sanchez",
    album: "Easy on My Eyes",
    year: "2021",
    audioUrl: "until_i_found_you.mp3",
    imageUrl: "images/until_i_found_you.jpg",
  ),
  Song(
    title: "We Will Rock You",
    artist: "Queen",
    album: "News of the World",
    year: "1977",
    audioUrl: "we_will_rock_you.mp3",
    imageUrl: "images/we_will_rock_you.jpg",
  ),
];
